services:
    mysql:
        image: mysql
        container_name: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_DATABASE: vppdb
            MYSQL_USER: vppuser
            MYSQL_PASSWORD: vpppassword
        ports:
            - "3306:3306"
        volumes:
            - mysql_data:/var/lib/mysql

    zookeeper:
        image: confluentinc/cp-zookeeper
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
        ports:
            - "22181:2181"
        volumes:
            - zookeeper_data:/var/lib/zookeeper
        restart: always

    kafka:
        image: confluentinc/cp-kafka
        depends_on:
            - zookeeper
        ports:
            - "29092:29092"
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_LOG_RETENTION_HOURS: 168
            KAFKA_LOG_RETENTION_BYTES: 1073741824
            KAFKA_NUM_PARTITIONS: 6
        volumes:
            - kafka_data:/var/lib/kafka/data
        restart: always

    kafka-ui:
        image: provectuslabs/kafka-ui
        depends_on:
            - kafka
        ports:
            - "8090:8080"
        environment:
            KAFKA_CLUSTERS_0_NAME: local
            KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
            KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
            KAFKA_UI_BASIC_AUTH_USER: admin
            KAFKA_UI_BASIC_AUTH_PASSWORD: secret
        restart: always

volumes:
    mysql_data:
    zookeeper_data:
        driver: local
    kafka_data:
        driver: local
