server:
    port: 8080

spring:
    cloud:
        gateway:
            globalcors:
                cors-configurations:
                    '[/**]':
                        allowedOriginPatterns: "*"
                        allowedMethods: GET, POST, PUT, DELETE, OPTIONS
                        allowedHeaders: "*"
                        allowCredentials: true
            routes:
                -   id: vpp-battery-mgr
                    uri: lb://vpp-battery-mgr
                    predicates:
                        - Path=/api/v1/batteries/**

    data:
        redis:
            host: localhost
            port: 6379
            password: vpp
            database: 0
            timeout: 2000ms
    application:
        name: vpp-gateway

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/
