server:
    port: 8080

spring:
    cloud:
        gateway:
            routes:
                - id: vpp-battery-mgr
                  uri: http://localhost:8081
                  predicates:
                      - Path=/api/v1/batteries/**
                  filters:
                      - RequestRateLimiter=redis-rate-limiter
                      - RewritePath=/api/v1/batteries/(?<segment>.*), /batteries/${segment}
                  metadata:
                      redis-rate-limiter:
                          replenishRate: 10
                          burstCapacity: 20
            default-filters:
                - name: JwtAuthenticationFilter

    data:
        redis:
            host: localhost
            port: 6379
            password: vpp
            database: 0
            timeout: 2000ms

jwt:
    secret: vpp-gateway
